version: '3'
services:
  sinatrilla:
    build: .
    container_name: "sinatrilla_container"
    ports:
     - "4567:4567"

  selenium:
    image: "selenium/standalone-chrome"
    container_name: "selenium_container"
    logging:
      driver: none
    expose:
      - "4444"
