version: '3'
services:
  web:
    build: .
    ports:
     - "4567:4567"

  selenium:
    image: "selenium/standalone-chrome"
    container_name: "selenium"
    logging:
      driver: none
    expose:
      - "4444"
